### ISSUE TITLE
WebJars (Maven Central) NPM

### ISSUE THREAD

**Issue by michaelvashchinsky** [dpiccone/ng-pageslide#117]
This is what I get while trying to publish the repo to WebJars:

```
Failed! The source repository for angular-pageslide-directive 1.4.0 could not be determined but is 
required to published to Maven Central. This will need to be fixed in the project's package metadata. If 
you feel you have reached this failure in error, please file an issue: 
https://github.com/webjars/webjars/issues  Determined Artifact Name: angular-pageslide-directive 
Starting Deploy
```

**Comment by dpiccone** [comment]
the git url was missing from package.json, in version 1.4.3 should be fixed

**Comment by mickeyvip** [comment]
There is still a problem. I think because of the typo in `package.json`.

There is a PR (https://github.com/dpiccone/ng-pageslide/pull/122) that should fix the issue.

**Comment by dpiccone** [comment]
merged that, now should be fine

**Comment by mickeyvip** [comment]
Strangely enough it still has a problem with WebJars:
![image](https://cloud.githubusercontent.com/assets/220427/16763620/4a5caa60-4832-11e6-9fbf-674cb8ab9a20.png)

**Comment by mickeyvip** [comment]
I just opened an issue https://github.com/webjars/webjars/issues/1431

**Comment by mickeyvip** [comment]
@dpiccone, I got an answer.

You need to update the release, WebJars take the version by tag and in that `zip` (`1.4.3`) there is still a typo in `license`.

Thanks

**Comment by dpiccone** [comment]
@mickeyvip just updated to v1.4.4 with the typo fix

**Comment by mickeyvip** [comment]
Now it's working!

Thank you!
